name = "demireller-group-db"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # Kod içinde bu isimle çağıracağız
database_name = "demireller-group-db"
database_id = "7fc70bf4-f1ca-4a14-97fa-1590ab1241b8"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "demireller-group-storage"